### ISSUE TITLE
Support for EC2 spot pricing

### ISSUE THREAD

**Issue by copumpkin** [NixOS/hydra-provisioner#1]
Seems like the next killer feature :smile:

**Comment by edolstra** [comment]
Hm, what does that mean exactly?

**Comment by copumpkin** [comment]
EC2 allows you to "bid" for instances below their official prices, and publishes current spot rates in machine- and [human-readable](https://aws.amazon.com/ec2/spot/pricing/) forms.

This means that you can say "I'm willing to pay $x/hour for an m3.medium" and it'll give you the instance as long as the price stays below your rate. For reproducible (and especially not long-running) builds this seems like a fine model. Long-running builds might be annoying because the instance can go away if the price goes up.

The price advantages can be pretty substantial. For example, in us-east-1e, an m3.medium over the past  month has averaged around $0.008/hour. The standard price is $0.067, which means you're paying basically 1/8 the price, with a risk that your instance can die. I haven't compared other instance types, but I expect there will be substantial potential savings.

I expect it's probably fairly tricky to support, but build servers seem like the ideal use for something like this.

**Comment by edolstra** [comment]
I'm currently using spot instances, so this works already :-) Hence my confusion.

(It's not perfect yet though - if the current price is above the bid, then "nixops deploy" will hang until the price drops sufficiently, and so the provisioner will hang as well...)

**Comment by edolstra** [comment]
See here for the config: https://github.com/NixOS/nixos-org-configurations/blob/master/hydra-provisioner/nixops.nix#L21

**Comment by copumpkin** [comment]
Oh! I didn't realize, awesome. I thought I'd grepped the file sufficiently, but I guess I failed. Will have to look more closely. Thanks again.

**Comment by copumpkin** [comment]
Hah, right below the line I commented on about the deprecated instance types! Goes to show how observant I am :smile:
